### ISSUE TITLE
Self is undefined when server rendering.

### ISSUE THREAD

**Issue by byavv** [mozilla/localForage#522]
I'm struggling with Angular2 server rendering via [Angular Universal](https://github.com/angular/universal). The main idea of that solution is that all Angular2 code executes in Node.js server. So, you can't use "self" variable in Node. When compiler runs my code where localforage is defined, I get: 

```javascript
node.exe : C:\Users\slava\dev\mea2n\node_modules\localforage\dist\localforage.js:1184
строка:1 знак:5
+ node <<<<  dist/server/server.js -n vd* -verbose 2>log.log
    + CategoryInfo          : NotSpecified: (C:\Users\slava\...lforage.js:1184:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    })(typeof window !== 'undefined' ? window : self);
                                                ^

ReferenceError: self is not defined
    at Object.exports.__esModule (C:\Users\slava\dev\mea2n\node_modules\localforage\dist\localforage.js:1184:46)
    at __webpack_require__ (C:\Users\slava\dev\mea2n\node_modules\localforage\dist\localforage.js:719:30)
    at exports.__esModule (C:\Users\slava\dev\mea2n\node_modules\localforage\dist\localforage.js:739:18)
    at C:\Users\slava\dev\mea2n\node_modules\localforage\dist\localforage.js:742:10
    at webpackUniversalModuleDefinition (C:\Users\slava\dev\mea2n\node_modules\localforage\dist\localforage.js:692:20)
    at Object.<anonymous> (C:\Users\slava\dev\mea2n\node_modules\localforage\dist\localforage.js:699:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.c (C:\Users\slava\dev\mea2n\dist\server\server.js:967:19)
    at __webpack_require__ (C:\Users\slava\dev\mea2n\dist\server\server.js:20:30)
    at Object.<anonymous> (C:\Users\slava\dev\mea2n\dist\server\server.js:907:20)
    at __webpack_require__ (C:\Users\slava\dev\mea2n\dist\server\server.js:20:30)

```
I'm not shure, that it's an issue of localforage itself, but  
```javascript
var globalObject =  Function('return this')(); 
// global in node
// window in browser
// worker global in web worker
```
solves my problem.

**Comment by tofumatt** [comment]
Thanks for the issue! Sadly, I don't think this is an issue with localForage.

Including `Function` like that isn't something we can include as it's likely to violate CSP rules and isn't a good practice.

We also don't focus on node support. If Angular Universal is meant to be drop-in I would file an issue with them.
