### ISSUE TITLE
Error building with gulp + browserify + babel

### ISSUE THREAD

**Issue by exos** [mozilla/localForage#578]
I have this error when i tried to browserify my app:

```
ReferenceError: [BABEL] /home/exos/projectv/node_modules/localforage/dist/localforage.js: Using removed Babel 5 option: /home/exos/projectv/node_modules/localforage/.babelrc.loose - Specify the `loose` option for the relevant plugin you are using or use a preset that sets the option.
    at Logger.error (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:20)
    at OptionManager.addConfig (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/home/exos/projectv/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/home/exos/projectv/node_modules/babelify/index.js:27:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
```

I install all babel plugins there are on the localForage package.json:

My package.json section:
```
  "devDependencies": {
    "angular-localforage": "^1.2.5",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-system-import-transformer": "^2.0.0",
    "babel-plugin-transform-es2015-modules-umd": "^6.8.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babelify": "^7.3.0",
    "brfs-htmlmin": "^2.0.0",
    "gulp": "^3.9.1",
    "gulp-browserify": "^0.5.1",
    "gulp-jshint": "^2.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.3.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.5.3",
    "ionic-material": "https://github.com/zachfitz/Ionic-Material.git#v0.4.2",
    "jshint": "^2.9.2",
    "jshint-stylish": "^2.2.0",
    "napa": "^2.3.0",
    "yargs": "^4.7.1"
 }
```

My gulp task:
```
gulp.task('build-lib', function () {

    var options = {
        insertGlobals : true,
        debug : argv.debug,
        shim: {
            angular: {
                path: "./node_modules/ionic/release/js/ionic.bundle.min.js",
                exports: "angular"
            }
        },
        extensions: [
            'es6'
        ],
        transform: [
            'babelify',
            'brfs-htmlmin'
        ]
    };

    return gulp.src(paths.lib)
        .pipe(sourcemaps.init())
        .pipe(browserify(options))
        .pipe(sourcemaps.write())
        .pipe(rename('app.js'))
        //.pipe(uglify())
        .pipe(rename('app.js'))
        .pipe(gulp.dest('www/js'));
});

```

my .babelrc
```
{
    "presets": ["es2015-loose"],
    "plugins": [
        "add-module-exports"
    ]
}
```

And I copied the file .babelrc-umd from the project. But I get the same error.

Some versions:
```
node: v5.11.1
npm: 3.8.6
```

**Comment by thgreasi** [comment]
What version of localforage do you end up using?

**Comment by exos** [comment]
Ok, then is a deep-dependencies problem on angular-localForage, I actually did installed that package, and aparently the last published version are old.

Checking the history of package.json: https://github.com/ocombe/angular-localForage/commits/master/package.json

The version 1.2.5 don't has [the patch that resolve it](https://github.com/ocombe/angular-localForage/commit/ee0ff97e673111a0e8c92344bcf2b9938c0cac1a).

The solution then It would be as simple as install first localForage and then install angular-localForage, like:

```
$ npm uninstall localForage angular-localForage
$ npm install --save-dev localForage
$ npm install --save-dev angular-localForage
```

Or directly do install angular-localForage#master

Thank you.

PS: Sorry my poor english :P

**Comment by thgreasi** [comment]
:+1: that was exactly what I was thinking!
